#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:
- job: win32_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh build.sh win32 all
      cd deploy
      7z a ../HelloSky.zip *
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-win32-qt5

- job: win64_qt5
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh build.sh win64 all
      cd deploy
      7z a ../HelloSky.zip *
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-win64-qt5

#--------------------------------------------------------------------------------------------------
# macOS
#--------------------------------------------------------------------------------------------------

- job: macOS_qt5
  pool:
    vmImage: "macOS-11"
  steps:
  - bash: |
      sh build.sh macOS all
      cd deploy
      zip -rq ../HelloSky.zip *
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-macOS-qt5

- job: macOS_qt6
  pool:
    vmImage: "macOS-11"
  steps:
  - bash: |
      sh environment.sh qt6
      sh build.sh macOS all
      cd deploy
      zip -rq ../HelloSky.zip *
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-macOS-qt6

#--------------------------------------------------------------------------------------------------
# iOS
#--------------------------------------------------------------------------------------------------

- job: iOS_qt5
  pool:
    # NOTE: macOS Big sur is required for iOS.
    vmImage: "macOS-14"
  steps:
  - bash: |
      sh build.sh iOS all
      cd deploy
      zip -rq ../HelloSky.zip *
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-iOS-qt5

- job: iOS_qt6
  pool:
    # NOTE: macOS Big sur is required for iOS.
    vmImage: "macOS-11"
  steps:
  - bash: |
      sh environment.sh qt6
      sh build.sh iOS all
      cd deploy
      zip -rq ../HelloSky.zip *
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-iOS-qt6

#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

- job: linux32_qt4
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/HelloSky i386/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /HelloSky;
                                     apt-get update;
                                     apt-get -y install sudo curl zip git;
                                     sh environment.sh qt4;
                                     sh build.sh linux all;
                                     cd deploy;
                                     zip -rq ../HelloSky.zip *"
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-linux32-qt4

- job: linux64_qt4
  pool:
    # NOTE: Ubuntu 20.04 seems to be required for qt4-default.
    vmImage: "ubuntu-20.04"
  steps:
  - bash: |
      sh environment.sh qt4
      sh build.sh linux all
      cd deploy
      zip -rq ../HelloSky.zip *
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-linux64-qt4

#--------------------------------------------------------------------------------------------------

- job: linux32_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/HelloSky i386/ubuntu:20.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /HelloSky;
                                     apt-get update;
                                     apt-get -y install sudo curl zip git;
                                     sh build.sh linux all;
                                     cd deploy;
                                     zip -rq ../HelloSky.zip *"
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-linux32-qt5

- job: linux64_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  # NOTE: We need an older version to package the application.
  - bash: |
      docker run -d --name ubuntu -v $PWD:/HelloSky amd64/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /HelloSky;
                                     apt-get update;
                                     apt-get -y install sudo curl zip git;
                                     sh build.sh linux all;
                                     cd deploy;
                                     zip -rq ../HelloSky.zip *"
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-linux64-qt5

#--------------------------------------------------------------------------------------------------

- job: linux64_qt6
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      sh environment.sh qt6
      sh build.sh linux all
      cd deploy
      zip -rq ../HelloSky.zip *
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-linux64-qt6

#--------------------------------------------------------------------------------------------------
# Android
#--------------------------------------------------------------------------------------------------

- job: android_qt5
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      sh build.sh android all
      cd deploy
      zip -rq ../HelloSky.zip *
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-android-qt5

- job: android_qt6
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      sh environment.sh qt6
      sh build.sh android all
      cd deploy
      zip -rq ../HelloSky.zip *
  - publish: $(System.DefaultWorkingDirectory)/HelloSky.zip
    artifact: HelloSky-android-qt6
